/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.engsof.poo3.gerenciadorDeTarefas.view;

import br.unifae.engsof.poo3.gerenciadorDeTarefas.controller.TarefaController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author android
 */
public class CadastraTarefasPrazo extends javax.swing.JFrame {

    /**
     * Creates new form CadastraTarefas
     */
    public CadastraTarefasPrazo() {
        initComponents();
      
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        jtxtCriacao.setText(LocalDate.now().format(formatter));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblDescricao = new javax.swing.JLabel();
        jlblPrior = new javax.swing.JLabel();
        jlblCriacao = new javax.swing.JLabel();
        jtxtDescricao = new javax.swing.JTextField();
        jcomboPrior = new javax.swing.JComboBox<>();
        jtxtCriacao = new javax.swing.JFormattedTextField();
        jlblPrazo = new javax.swing.JLabel();
        jtxtPrazo = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastra Tarefas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Obrigatórios"));

        jlblDescricao.setLabelFor(jtxtDescricao);
        jlblDescricao.setText("Descrição:");

        jlblPrior.setLabelFor(jcomboPrior);
        jlblPrior.setText("Prioridade:");

        jlblCriacao.setLabelFor(jtxtCriacao);
        jlblCriacao.setText("Data de Criação:");

        jcomboPrior.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        try {
            jtxtCriacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlblPrazo.setLabelFor(jtxtCriacao);
        jlblPrazo.setText("Data Limite:");

        try {
            jtxtPrazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCriacao)
                    .addComponent(jlblPrior)
                    .addComponent(jlblDescricao)
                    .addComponent(jlblPrazo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboPrior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDescricao)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPrior)
                    .addComponent(jcomboPrior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCriacao)
                    .addComponent(jtxtCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPrazo)
                    .addComponent(jtxtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButtonSalvar)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String descricao = jtxtDescricao.getText();
        int prioridade = Integer.parseInt((String)jcomboPrior.getSelectedItem());
        String data = jtxtCriacao.getText();
        String data2 = jtxtPrazo.getText();
        
        if("".equals(descricao)){
            JOptionPane.showMessageDialog(null, "Campo descrição vazio", "Aviso", 0);
        } else if("  /  /    ".equals(data)){
               JOptionPane.showMessageDialog(null, "Campo data criação vazio ou incompleto", "Aviso", 0);
        } else if("  /  /    ".equals(data2)){
                   JOptionPane.showMessageDialog(null, "Campo de prazo vazio ou incompleto", "Aviso", 0);
        } else {
            TarefaController tarefaController = new TarefaController();
            try {
                LocalDate dataCriacao = LocalDate.parse(data,DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                LocalDate dataPrazo = LocalDate.parse(data2,DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                int resposta = JOptionPane.YES_NO_OPTION;
                if(dataPrazo.isBefore(dataCriacao)){
                        resposta = JOptionPane.showConfirmDialog(
                        null,
                        "Data de Prazo menor que a data de criação, tem certeza que deseja cadastrar assim?",
                        "Aviso",
                        JOptionPane.YES_NO_OPTION
                    );
                }
                if(resposta == JOptionPane.YES_OPTION){
                    if(tarefaController.addTarefaPrazo(descricao,prioridade, dataCriacao, dataPrazo)){
                        JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso", "Sucesso", 1);
                        jtxtDescricao.setText("");
                        jcomboPrior.setSelectedItem("1");
                        jtxtPrazo.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao cadastrar o produto, revise os dados inseridos", "Erro", 0);
                    }
                }
                
            } catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Campos de data com formato ou valores invalidos", "Aviso", 0);
            }
        }   
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jtxtPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraTarefasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraTarefasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraTarefasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraTarefasSimples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraTarefasPrazo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcomboPrior;
    private javax.swing.JLabel jlblCriacao;
    private javax.swing.JLabel jlblDescricao;
    private javax.swing.JLabel jlblPrazo;
    private javax.swing.JLabel jlblPrior;
    private javax.swing.JFormattedTextField jtxtCriacao;
    private javax.swing.JTextField jtxtDescricao;
    private javax.swing.JFormattedTextField jtxtPrazo;
    // End of variables declaration//GEN-END:variables
}
