/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.engsof.poo3.gerenciadorDeTarefas.view;

/**
 *
 * @author Igor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastrar = new javax.swing.JMenu();
        MenuCad1 = new javax.swing.JMenuItem();
        MenuCad2 = new javax.swing.JMenuItem();
        MenuListar = new javax.swing.JMenu();
        MenuList1 = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCadastrar.setText("Cadastrar");
        MenuCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenuCad1.setText("Tarefa Simples");
        MenuCad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCad1ActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MenuCad1);

        MenuCad2.setText("Tarefa com Prazo");
        MenuCad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCad2ActionPerformed(evt);
            }
        });
        MenuCadastrar.add(MenuCad2);

        jMenuBar1.add(MenuCadastrar);

        MenuListar.setText("Listar");
        MenuListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        MenuList1.setText("Tarefas");
        MenuList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuList1ActionPerformed(evt);
            }
        });
        MenuListar.add(MenuList1);

        jMenuBar1.add(MenuListar);

        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCad1ActionPerformed
        this.dispose();
        CadastraTarefasSimples cad = new CadastraTarefasSimples();
        cad.setVisible(true);
    }//GEN-LAST:event_MenuCad1ActionPerformed

    private void MenuList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuList1ActionPerformed
        this.dispose();
        ListarTarefas lista = new ListarTarefas();
        lista.setVisible(true);
    }//GEN-LAST:event_MenuList1ActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_MenuSairMouseClicked

    private void MenuCad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCad2ActionPerformed
        this.dispose();
        CadastraTarefasPrazo cad = new CadastraTarefasPrazo();
        cad.setVisible(true);
    }//GEN-LAST:event_MenuCad2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCad1;
    private javax.swing.JMenuItem MenuCad2;
    private javax.swing.JMenu MenuCadastrar;
    private javax.swing.JMenuItem MenuList1;
    private javax.swing.JMenu MenuListar;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
